//
//  IconLibrary.swift
//  Markly
//

import Foundation

// MARK: - Icon

struct MarklyIcon: Identifiable, Hashable {
    let id: String          // unique key, used to store in model
    let isCustom: Bool      // true = asset catalog

    init(_ id: String, custom: Bool = true) {
        self.id = id
        self.isCustom = custom
    }
}

// MARK: - Icon Category

struct IconCategory {
    let name: String
    let icons: [MarklyIcon]
}

// MARK: - Library

enum IconLibrary {
    static let categories: [IconCategory] = [

        IconCategory(name: "Bookmarks & Books", icons: [
            MarklyIcon("flatbook",          custom: true),
            MarklyIcon("openbook",          custom: true),
            MarklyIcon("doublebooks",       custom: true),
            MarklyIcon("moonbook",          custom: true),
            MarklyIcon("pentbook",          custom: true),
            MarklyIcon("moodbook",          custom: true),
            MarklyIcon("starmark",          custom: true),
            MarklyIcon("bookopen",          custom: true),
            MarklyIcon("openbookhands",     custom: true),
            MarklyIcon("standopenbook",     custom: true),
            MarklyIcon("reading",           custom: true),
            MarklyIcon("reader",            custom: true),
            MarklyIcon("ebook",             custom: true),
            MarklyIcon("sparklebook",       custom: true),
            MarklyIcon("magicbook",         custom: true),
            MarklyIcon("cutedecorjournal",  custom: true),
            MarklyIcon("cutebookbag",       custom: true),
            MarklyIcon("circlemark",        custom: true),
            MarklyIcon("circlemarked",      custom: true),
            MarklyIcon("books",             custom: true),
            MarklyIcon("markedbook",        custom: true),
            MarklyIcon("bookedmark",        custom: true),
            MarklyIcon("blankpages",        custom: true),
            MarklyIcon("markbookcircle",    custom: true),
            MarklyIcon("dashmark",          custom: true),
            MarklyIcon("savesparkle",       custom: true),
            MarklyIcon("searchwavy",        custom: true),
            MarklyIcon("webpage",           custom: true),
            MarklyIcon("browserpage",       custom: true),
            MarklyIcon("starwebpage",       custom: true),
            MarklyIcon("starrybook",        custom: true),
            MarklyIcon("timebook",          custom: true),
            MarklyIcon("lockheartjournal",  custom: true),
            MarklyIcon("stackofbooks",      custom: true),
        ]),

        IconCategory(name: "Rooms", icons: [
            MarklyIcon("houseoutline",      custom: true),
            MarklyIcon("housefill",         custom: true),
            MarklyIcon("couch",             custom: true),
            MarklyIcon("livingroom",        custom: true),
            MarklyIcon("curtains",          custom: true),
            MarklyIcon("armchair",          custom: true),
            MarklyIcon("flatscreen",        custom: true),
            MarklyIcon("sidetable",         custom: true),
            MarklyIcon("tvstand",           custom: true),
            MarklyIcon("sofa",              custom: true),
            MarklyIcon("ottoman",           custom: true),
            MarklyIcon("vanity",            custom: true),
            MarklyIcon("lamp",              custom: true),
            MarklyIcon("lamptable",         custom: true),
            MarklyIcon("bathtubfill",       custom: true),
            MarklyIcon("fireplace",         custom: true),
            MarklyIcon("showerhead",        custom: true),
            MarklyIcon("showercurtain",     custom: true),
            MarklyIcon("television",        custom: true),
            MarklyIcon("window",            custom: true),
            MarklyIcon("shellwindow",       custom: true),
            MarklyIcon("signs",             custom: true),
            MarklyIcon("fridge",            custom: true),
            MarklyIcon("refrigerator",      custom: true),
            MarklyIcon("microwave",         custom: true),
            MarklyIcon("oven",              custom: true),
            MarklyIcon("dishwasher",        custom: true),
            MarklyIcon("bed",               custom: true),
            MarklyIcon("bedd",              custom: true),
            MarklyIcon("pillows",           custom: true),
            MarklyIcon("dresser",           custom: true),
            MarklyIcon("dressor",           custom: true),
            MarklyIcon("clothescloset",     custom: true),
            MarklyIcon("mirror",            custom: true),
            MarklyIcon("mirrordressor",     custom: true),
            MarklyIcon("sink",              custom: true),
            MarklyIcon("sinkstand",         custom: true),
            MarklyIcon("toilet",            custom: true),
            MarklyIcon("toiletfill",        custom: true),
            MarklyIcon("spiceshelf",        custom: true),
            MarklyIcon("bookshelf",         custom: true),
            MarklyIcon("washer",            custom: true),
            MarklyIcon("clothesbasket",     custom: true),
            MarklyIcon("buggy",             custom: true),
            MarklyIcon("starwindow",        custom: true),
            MarklyIcon("entrance",          custom: true),
            MarklyIcon("office",            custom: true),
            MarklyIcon("garage",            custom: true),
            MarklyIcon("windowheart",       custom: true),
            MarklyIcon("hangingphoto",      custom: true),
        ]),

        IconCategory(name: "Cleaning", icons: [
            MarklyIcon("vacuum",            custom: true),
            MarklyIcon("vacuumcleaner",     custom: true),
            MarklyIcon("broompan",          custom: true),
            MarklyIcon("duster",            custom: true),
            MarklyIcon("sponge",            custom: true),
            MarklyIcon("bucket",            custom: true),
            MarklyIcon("mopping",           custom: true),
            MarklyIcon("spraybottle",       custom: true),
            MarklyIcon("spraybroom",        custom: true),
            MarklyIcon("spraycleaner",      custom: true),
            MarklyIcon("detergent",         custom: true),
            MarklyIcon("washmachine",       custom: true),
            MarklyIcon("bottlesoap",        custom: true),
            MarklyIcon("soapdishes",        custom: true),
            MarklyIcon("soapsbasket",       custom: true),
            MarklyIcon("beautybottle",      custom: true),
            MarklyIcon("lotion",            custom: true),
            MarklyIcon("rollpaper",         custom: true),
            MarklyIcon("toiletpaper",       custom: true),
            MarklyIcon("towel",             custom: true),
            MarklyIcon("fulltrash",         custom: true),
            MarklyIcon("trashfill",         custom: true),
            MarklyIcon("flatiron",          custom: true),
            MarklyIcon("lovedryer",         custom: true),
        ]),

        IconCategory(name: "Kitchen", icons: [
            MarklyIcon("silverware",        custom: true),
            MarklyIcon("teapot",            custom: true),
            MarklyIcon("coffeemaker",       custom: true),
            MarklyIcon("takeoutcoffee",     custom: true),
            MarklyIcon("rainbowmug",        custom: true),
            MarklyIcon("mugandtray",        custom: true),
            MarklyIcon("groceries",         custom: true),
            MarklyIcon("dropfill",          custom: true),
            MarklyIcon("flamefill",         custom: true),
            MarklyIcon("ovenmit",           custom: true),
            MarklyIcon("diningtable",       custom: true),
            MarklyIcon("kitchentable",      custom: true),
            MarklyIcon("bottle",            custom: true),
            MarklyIcon("glassfill",         custom: true),
            MarklyIcon("energydrink",       custom: true),
            MarklyIcon("jugfill",           custom: true),
        ]),

        IconCategory(name: "Love & Calendar", icons: [
            MarklyIcon("heartlist",         custom: true),
            MarklyIcon("pagelovelist",      custom: true),
            MarklyIcon("lovedotlist",       custom: true),
            MarklyIcon("lovedotprogress",   custom: true),
            MarklyIcon("lovemusic",         custom: true),
            MarklyIcon("lovemusicnote",     custom: true),
            MarklyIcon("loveletter",        custom: true),
            MarklyIcon("lovelycal",         custom: true),
            MarklyIcon("lovelinedcal",      custom: true),
            MarklyIcon("loveboxcal",        custom: true),
            MarklyIcon("lovefloat",         custom: true),
            MarklyIcon("lovetickets",       custom: true),
            MarklyIcon("lovecal",           custom: true),
            MarklyIcon("lovebox",           custom: true),
            MarklyIcon("loveflame",         custom: true),
            MarklyIcon("loveflames",        custom: true),
            MarklyIcon("loveinfinity",      custom: true),
            MarklyIcon("loveeye",           custom: true),
            MarklyIcon("lovelookglass",     custom: true),
            MarklyIcon("lovelinebook",      custom: true),
            MarklyIcon("lovepopcake",       custom: true),
            MarklyIcon("lovetarget",        custom: true),
            MarklyIcon("loveflag",          custom: true),
            MarklyIcon("locationlove",      custom: true),
            MarklyIcon("docslove",          custom: true),
            MarklyIcon("docsheart",         custom: true),
            MarklyIcon("lovedotsdoc",       custom: true),
            MarklyIcon("calendarlove",      custom: true),
            MarklyIcon("calhearts",         custom: true),
            MarklyIcon("heartboxcal",       custom: true),
            MarklyIcon("heartlinescal",     custom: true),
            MarklyIcon("twinlovecal",       custom: true),
            MarklyIcon("xoxocal",           custom: true),
            MarklyIcon("numcal",            custom: true),
            MarklyIcon("circlescal",        custom: true),
            MarklyIcon("starcal",           custom: true),
            MarklyIcon("dotcal",            custom: true),
            MarklyIcon("heartcalendar",     custom: true),
            MarklyIcon("heartunlock",       custom: true),
            MarklyIcon("luvmail",           custom: true),
            MarklyIcon("lovelocation",      custom: true),
            MarklyIcon("heartballoon",      custom: true),
            MarklyIcon("loveballoon",       custom: true),
            MarklyIcon("plusheart",         custom: true),
            MarklyIcon("lovejacket",        custom: true),
            MarklyIcon("lovepump",          custom: true),
            MarklyIcon("lovedropper",       custom: true),
            MarklyIcon("lovesmokes",        custom: true),
            MarklyIcon("loveinvite",        custom: true),
            MarklyIcon("lovebrochure",      custom: true),
            MarklyIcon("twinhearts",        custom: true),
            MarklyIcon("gesturelove",       custom: true),
            MarklyIcon("heartphone",        custom: true),
            MarklyIcon("bulbxoxo",          custom: true),
            MarklyIcon("xoxobulb",          custom: true),
            MarklyIcon("worldlove",         custom: true),
            MarklyIcon("ringstarcal",       custom: true),
            MarklyIcon("batcal",            custom: true),
        ]),

        IconCategory(name: "Charts & Social", icons: [
            MarklyIcon("chartup",           custom: true),
            MarklyIcon("chartdown",         custom: true),
            MarklyIcon("arrowchart",        custom: true),
            MarklyIcon("piechart",          custom: true),
            MarklyIcon("starcirclechart",   custom: true),
            MarklyIcon("starchart",         custom: true),
            MarklyIcon("socialdevice",      custom: true),
            MarklyIcon("socialphone",       custom: true),
            MarklyIcon("socialmedia",       custom: true),
            MarklyIcon("socialgroup",       custom: true),
            MarklyIcon("socialchat",        custom: true),
            MarklyIcon("webchat",           custom: true),
            MarklyIcon("pagechat",          custom: true),
            MarklyIcon("dotschat",          custom: true),
            MarklyIcon("doublelineschat",   custom: true),
            MarklyIcon("phone",             custom: true),
            MarklyIcon("linesphone",        custom: true),
            MarklyIcon("mediaphone",        custom: true),
            MarklyIcon("sparklephone",      custom: true),
            MarklyIcon("iphonesparkle",     custom: true),
            MarklyIcon("appsphone",         custom: true),
            MarklyIcon("appsiphone",        custom: true),
            MarklyIcon("medialinesphone",   custom: true),
            MarklyIcon("bowphone",          custom: true),
            MarklyIcon("appsdevice",        custom: true),
            MarklyIcon("instagram",         custom: true),
            MarklyIcon("discord",           custom: true),
            MarklyIcon("threads",           custom: true),
            MarklyIcon("facebook",          custom: true),
            MarklyIcon("github",            custom: true),
            MarklyIcon("starnet",           custom: true),
            MarklyIcon("group",             custom: true),
            MarklyIcon("chatlines",         custom: true),
            MarklyIcon("starphone",         custom: true),
            MarklyIcon("internetcircle",    custom: true),
            MarklyIcon("wificircle",        custom: true),
            MarklyIcon("fullsignal",        custom: true),
            MarklyIcon("signal",            custom: true),
            MarklyIcon("rss",               custom: true),
            MarklyIcon("thefeed",           custom: true),
            MarklyIcon("browsericon",       custom: true),
            MarklyIcon("mail",              custom: true),
            MarklyIcon("share",             custom: true),
            MarklyIcon("sendbutton",        custom: true),
            MarklyIcon("cloud",             custom: true),
            MarklyIcon("link",              custom: true),
            MarklyIcon("linkincoming",      custom: true),
            MarklyIcon("circlemusicnote",   custom: true),
        ]),

        IconCategory(name: "Tags & Shapes", icons: [
            MarklyIcon("linesbmark",        custom: true),
            MarklyIcon("shapelovetag",      custom: true),
            MarklyIcon("taglove",           custom: true),
            MarklyIcon("lovetag",           custom: true),
            MarklyIcon("startag",           custom: true),
            MarklyIcon("colorpicker",       custom: true),
            MarklyIcon("circledothashtag",  custom: true),
            MarklyIcon("blocks",            custom: true),
            MarklyIcon("blackbox",          custom: true),
            MarklyIcon("boxstack",          custom: true),
            MarklyIcon("bbblocks",          custom: true),
            MarklyIcon("babyblock",         custom: true),
            MarklyIcon("childrensblocks",   custom: true),
            MarklyIcon("bblocks",           custom: true),
            MarklyIcon("puzzlepiece",       custom: true),
            MarklyIcon("puzzlehand",        custom: true),
            MarklyIcon("circlepencil",      custom: true),
            MarklyIcon("circleimage",       custom: true),
            MarklyIcon("linescard",         custom: true),
            MarklyIcon("shapes",            custom: true),
            MarklyIcon("objects",           custom: true),
            MarklyIcon("popper",            custom: true),
            MarklyIcon("sparkleblocks",     custom: true),
            MarklyIcon("linkcircle",        custom: true),
            MarklyIcon("starcard",          custom: true),
            MarklyIcon("blanksign",         custom: true),
        ]),

        IconCategory(name: "Office & Tech", icons: [
            MarklyIcon("cellphone",         custom: true),
            MarklyIcon("apple",             custom: true),
            MarklyIcon("desktop",           custom: true),
            MarklyIcon("tabletdevice",      custom: true),
            MarklyIcon("writepencil",       custom: true),
            MarklyIcon("settings",          custom: true),
            MarklyIcon("settingscontrol",   custom: true),
            MarklyIcon("copyfill",          custom: true),
            MarklyIcon("exit",              custom: true),
            MarklyIcon("doorexit",          custom: true),
            MarklyIcon("lockwavy",          custom: true),
            MarklyIcon("devwindow",         custom: true),
            MarklyIcon("eyeoff",            custom: true),
            MarklyIcon("eyeon",             custom: true),
            MarklyIcon("folder",            custom: true),
            MarklyIcon("plainfolder",       custom: true),
            MarklyIcon("blankfolder",       custom: true),
            MarklyIcon("folderfill",        custom: true),
            MarklyIcon("openfolder",        custom: true),
            MarklyIcon("linedfolderfill",   custom: true),
            MarklyIcon("folderhand",        custom: true),
            MarklyIcon("folderchat",        custom: true),
            MarklyIcon("treefolder",        custom: true),
            MarklyIcon("description",       custom: true),
            MarklyIcon("cogwavy",           custom: true),
            MarklyIcon("circlefingerprint", custom: true),
            MarklyIcon("fingerprint",       custom: true),
            MarklyIcon("handkey",           custom: true),
            MarklyIcon("scope",             custom: true),
            MarklyIcon("play",              custom: true),
            MarklyIcon("forward",           custom: true),
            MarklyIcon("image",             custom: true),
            MarklyIcon("laptop",            custom: true),
            MarklyIcon("pencilfill",        custom: true),
            MarklyIcon("controls",          custom: true),
            MarklyIcon("tools",             custom: true),
            MarklyIcon("toolsfilled",       custom: true),
            MarklyIcon("toolshand",         custom: true),
            MarklyIcon("inboxfill",         custom: true),
            MarklyIcon("emptyinbox",        custom: true),
            MarklyIcon("fullfolder",        custom: true),
            MarklyIcon("pininnote",         custom: true),
            MarklyIcon("tabs",              custom: true),
            MarklyIcon("refresh",           custom: true),
            MarklyIcon("repeat",            custom: true),
            MarklyIcon("arrows",            custom: true),
            MarklyIcon("crossarrowscircle", custom: true),
            MarklyIcon("profilearrowscircle", custom: true),
            MarklyIcon("arrowprofile",      custom: true),
            MarklyIcon("download",          custom: true),
            MarklyIcon("cloudsync",         custom: true),
            MarklyIcon("flopdisk",          custom: true),
            MarklyIcon("linedmarker",       custom: true),
            MarklyIcon("toolswebpage",      custom: true),
            MarklyIcon("bug",               custom: true),
            MarklyIcon("warnwavy",          custom: true),
        ]),

        IconCategory(name: "Wellness & Self-Care", icons: [
            MarklyIcon("heartfill",         custom: true),
            MarklyIcon("heartoutline",      custom: true),
            MarklyIcon("heartwavy",         custom: true),
            MarklyIcon("heartlines",        custom: true),
            MarklyIcon("hearteye",          custom: true),
            MarklyIcon("halfheart",         custom: true),
            MarklyIcon("heartpage",         custom: true),
            MarklyIcon("pawprint",          custom: true),
            MarklyIcon("healthwatch",       custom: true),
            MarklyIcon("moonzzz",           custom: true),
            MarklyIcon("sparkle",           custom: true),
            MarklyIcon("sparkbolt",         custom: true),
            MarklyIcon("circlesparkles",    custom: true),
            MarklyIcon("circleheart",       custom: true),
            MarklyIcon("bell",              custom: true),
            MarklyIcon("medbottle",         custom: true),
            MarklyIcon("bandageheart",      custom: true),
            MarklyIcon("rattles",           custom: true),
            MarklyIcon("bbypiano",          custom: true),
            MarklyIcon("pills",             custom: true),
            MarklyIcon("pillhand",          custom: true),
            MarklyIcon("singlepill",        custom: true),
            MarklyIcon("doublepills",       custom: true),
            MarklyIcon("health",            custom: true),
            MarklyIcon("medicon",           custom: true),
            MarklyIcon("mind",              custom: true),
            MarklyIcon("pulseheart",        custom: true),
            MarklyIcon("bubbles",           custom: true),
            MarklyIcon("nailpolish",        custom: true),
            MarklyIcon("nailsparkle",       custom: true),
            MarklyIcon("hairbrush",         custom: true),
            MarklyIcon("meditation",        custom: true),
            MarklyIcon("zenrocks",          custom: true),
            MarklyIcon("tooth",             custom: true),
            MarklyIcon("rxbottle",          custom: true),
            MarklyIcon("dumbbell",          custom: true),
            MarklyIcon("spiralmind",        custom: true),
            MarklyIcon("creambottle",       custom: true),
            MarklyIcon("bones",             custom: true),
            MarklyIcon("razor",             custom: true),
            MarklyIcon("mooncream",         custom: true),
        ]),

        IconCategory(name: "Stars & Awards", icons: [
            MarklyIcon("starfill",          custom: true),
            MarklyIcon("staroutline",       custom: true),
            MarklyIcon("staroutlinetrophy", custom: true),
            MarklyIcon("starwavy",          custom: true),
            MarklyIcon("startrophy",        custom: true),
            MarklyIcon("startrophyfill",    custom: true),
            MarklyIcon("startrophyfilled",  custom: true),
            MarklyIcon("startrophyhand",    custom: true),
            MarklyIcon("startrophyhands",   custom: true),
            MarklyIcon("circlestar",        custom: true),
            MarklyIcon("linesstar",         custom: true),
            MarklyIcon("rainbow",           custom: true),
            MarklyIcon("searchsparkle",     custom: true),
            MarklyIcon("targetsparkle",     custom: true),
            MarklyIcon("tagsparkle",        custom: true),
            MarklyIcon("brightbulb",        custom: true),
            MarklyIcon("devbulb",           custom: true),
            MarklyIcon("handbulb",          custom: true),
            MarklyIcon("starbulb",          custom: true),
            MarklyIcon("starnote",          custom: true),
            MarklyIcon("stardoc",           custom: true),
            MarklyIcon("stardotdocs",       custom: true),
            MarklyIcon("starpopgift",       custom: true),
            MarklyIcon("stargifttag",       custom: true),
            MarklyIcon("handstar",          custom: true),
            MarklyIcon("starhand",          custom: true),
            MarklyIcon("starinhand",        custom: true),
            MarklyIcon("starhandtrophy",    custom: true),
            MarklyIcon("starburst",         custom: true),
            MarklyIcon("starshield",        custom: true),
            MarklyIcon("starbullets",       custom: true),
            MarklyIcon("starballoons",      custom: true),
            MarklyIcon("sparklebolt",       custom: true),
            MarklyIcon("sparklesearch",     custom: true),
            MarklyIcon("sparklearrowprogress", custom: true),
            MarklyIcon("sparklesstarflag",  custom: true),
            MarklyIcon("goalsparkle",       custom: true),
            MarklyIcon("circletrophy",      custom: true),
            MarklyIcon("trophyribbon",      custom: true),
            MarklyIcon("trophybars",        custom: true),
            MarklyIcon("stargift",          custom: true),
            MarklyIcon("starmailing",       custom: true),
            MarklyIcon("starfolder",        custom: true),
            MarklyIcon("starchat",          custom: true),
            MarklyIcon("starladder",        custom: true),
            MarklyIcon("starpinlocation",   custom: true),
            MarklyIcon("startarget",        custom: true),
            MarklyIcon("starbars",          custom: true),
            MarklyIcon("starcircleprogress", custom: true),
            MarklyIcon("starlooptag",       custom: true),
            MarklyIcon("starsparklesbox",   custom: true),
            MarklyIcon("statsupsparkle",    custom: true),
            MarklyIcon("boltcircleprogress", custom: true),
        ]),

        IconCategory(name: "Outdoors & Storage", icons: [
            MarklyIcon("yard",              custom: true),
            MarklyIcon("treeoutside",       custom: true),
            MarklyIcon("hanger",            custom: true),
            MarklyIcon("sun",               custom: true),
            MarklyIcon("planet",            custom: true),
            MarklyIcon("shoe",              custom: true),
            MarklyIcon("kitty",             custom: true),
            MarklyIcon("doggie",            custom: true),
            MarklyIcon("doghouse",          custom: true),
            MarklyIcon("paw",               custom: true),
            MarklyIcon("petfood",           custom: true),
            MarklyIcon("petmeds",           custom: true),
            MarklyIcon("jackolantern",      custom: true),
            MarklyIcon("ghost",             custom: true),
            MarklyIcon("flowerbasket",      custom: true),
            MarklyIcon("flower",            custom: true),
            MarklyIcon("decoreggs",         custom: true),
        ]),

        IconCategory(name: "Money & Shopping", icons: [
            MarklyIcon("moneybills",        custom: true),
            MarklyIcon("lovemoney",         custom: true),
            MarklyIcon("shopbasket",        custom: true),
            MarklyIcon("market",            custom: true),
            MarklyIcon("pigbank",           custom: true),
            MarklyIcon("walletfill",        custom: true),
            MarklyIcon("creditcard",        custom: true),
            MarklyIcon("visacard",          custom: true),
            MarklyIcon("carthand",          custom: true),
            MarklyIcon("billsfile",         custom: true),
            MarklyIcon("moneybaghands",     custom: true),
            MarklyIcon("threecoins",        custom: true),
            MarklyIcon("packagefill",       custom: true),
        ]),

        IconCategory(name: "Art & Writing", icons: [
            MarklyIcon("artboard",          custom: true),
            MarklyIcon("paintbrush",        custom: true),
            MarklyIcon("paintdrop",         custom: true),
            MarklyIcon("paintsparkle",      custom: true),
            MarklyIcon("lineswrite",        custom: true),
            MarklyIcon("pencil",            custom: true),
            MarklyIcon("writingpencil",     custom: true),
            MarklyIcon("writefeather",      custom: true),
            MarklyIcon("pencilsoverlap",    custom: true),
            MarklyIcon("pencilinlines",     custom: true),
            MarklyIcon("handbook",          custom: true),
            MarklyIcon("sticky",            custom: true),
            MarklyIcon("mailbox",           custom: true),
            MarklyIcon("mailboxtop",        custom: true),
            MarklyIcon("stickywrite",       custom: true),
        ]),

        IconCategory(name: "Misc", icons: [
            MarklyIcon("calendarfill",      custom: true),
            MarklyIcon("clockfill",         custom: true),
            MarklyIcon("clockwavy",         custom: true),
            MarklyIcon("boltfill",          custom: true),
            MarklyIcon("levelup",           custom: true),
            MarklyIcon("hashtag",           custom: true),
            MarklyIcon("hashtagwavy",       custom: true),
            MarklyIcon("micfill",           custom: true),
            MarklyIcon("minuswavy",         custom: true),
            MarklyIcon("skipwavy",          custom: true),
            MarklyIcon("pausewavy",         custom: true),
            MarklyIcon("stopwavy",          custom: true),
            MarklyIcon("playwavy",          custom: true),
            MarklyIcon("playtv",            custom: true),
            MarklyIcon("movietix",          custom: true),
            MarklyIcon("megafill",          custom: true),
            MarklyIcon("timewavy",          custom: true),
            MarklyIcon("wand",              custom: true),
            MarklyIcon("yinyang",           custom: true),
            MarklyIcon("crystalball",       custom: true),
            MarklyIcon("aries",             custom: true),
            MarklyIcon("aquarius",          custom: true),
            MarklyIcon("cancer",            custom: true),
            MarklyIcon("capricorn",         custom: true),
            MarklyIcon("gemini",            custom: true),
            MarklyIcon("leo",               custom: true),
            MarklyIcon("libra",             custom: true),
            MarklyIcon("pisces",            custom: true),
            MarklyIcon("sagittarius",       custom: true),
            MarklyIcon("scorpio",           custom: true),
            MarklyIcon("taurus",            custom: true),
            MarklyIcon("virgo",             custom: true),
            MarklyIcon("listcircle",        custom: true),
            MarklyIcon("clockhand",         custom: true),
        ]),

        // UI icons — used throughout the app, not shown in pickers
        IconCategory(name: "UI", icons: [
            MarklyIcon("checkwavy",         custom: true),
            MarklyIcon("xmark",             custom: true),
            MarklyIcon("reset",             custom: true),
            MarklyIcon("hourglassfill",     custom: true),
            MarklyIcon("pinfill",           custom: true),
            MarklyIcon("userwavy",          custom: true),
            MarklyIcon("liststars",         custom: true),
            MarklyIcon("archive",           custom: true),
            MarklyIcon("chevright",         custom: true),
            MarklyIcon("chevleft",          custom: true),
            MarklyIcon("chevup",            custom: true),
            MarklyIcon("chevdown",          custom: true),
            MarklyIcon("addwavy",           custom: true),
            MarklyIcon("dotswavy",          custom: true),
        ]),
    ]

    /// All categories shown in the icon picker (excludes UI and Catalog)
    static let pickerCategories: [IconCategory] = categories.filter {
        $0.name != "UI"
    }

    /// Flat list of all icons(includes UI)
    static let all: [MarklyIcon] = categories.flatMap { $0.icons }

    /// Flat list of picker icons only
    static let pickerIcons: [MarklyIcon] = pickerCategories.flatMap { $0.icons }
}
